### PR TITLE
Replace Demo Screenshot With GIF

### PR DESCRIPTION
**Pull request by Evavic44**
## Description

Replaced demo screenshot with animated gif

Fixes # 
#14 
### Type of change
Update

- [x] Updated documentation (updated the readme, templates, or other repo files)

## Checklist:

- [x] The code is properly formatted and is consistent with the existing code style
- [x] I have checked to make sure no other pull requests are open for this issue
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Evavic44** [comment]
I forgot that I switched to dark mode. If you want the light version, I can make it.

**Comment by DenverCoder1** [comment]
Very nice 👏

Thanks for working on this! 👍

A few things to consider:

* The text entered is a bit longer than 400 pixels so it gets cut off. You may want to show in the GIF that adjusting the width field can solve this.
* Only one line was entered, however, there is support for multiple lines. Maybe adding a second line would be a feature to include in the GIF.
* Although `Arial` works since it's installed on your computer, the font field is meant for [Google fonts](https://fonts.google.com/) only so it works across all devices. If you change the font, maybe try something like `Roboto` instead.
* The colors seem to have gotten a bit distorted possibly from some compression. Maybe see if there's a way to avoid that, possibly with different software? If that's not possible, it's fine.

Dark mode is fine, but light mode is preferable I think, since it's the default.

Thanks for your help!

**Comment by Evavic44** [comment]
Yeah. All valid observations. I'll work on it again with these pointers. Thank you.

**Comment by Evavic44** [comment]
### New Gif Added
#### Changes I made
- Entered the same number of text but didn't touch the width, so text won't shrink or cut.
- [x] Added a second line as requested.
- `Roboto` didn't work for some reason, so I used `Times New Roman` 🤔 Not sure, but should be available on all devices
- [x] Made some tweaking to correct the color distortion.
- [x] And of course, switched to light mode. 😄 

_Sorry about the extra commits, had some trouble updating my forked repo. Was thinking of deleting my fork and creating a clean PR_

**Comment by DenverCoder1** [comment]
Thanks, you've helped notice an issue which is that Google Fonts actually can't be loaded through images. The way the code works right now, is it tries to create a Google Fonts url from the font name (which is why it shouldn't be something like Arial or Times New Roman), but it currently only works if your computer has the font.

I will try to fix this issue so Google Fonts can be loaded, but Times New Roman should also be fine.

The new GIF looks good! :+1:

**Review by DenverCoder1 — APPROVED** [review]
Thanks for contributing!

**Comment by Evavic44** [comment]
> Thanks, you've helped notice an issue which is that Google Fonts actually can't be loaded through images. The way the code works right now, is it tries to create a Google Fonts url from the font name (which is why it shouldn't be something like Arial or Times New Roman), but it currently only works if your computer has the font.
> 
> I will try to fix this issue so Google Fonts can be loaded, but Times New Roman should also be fine.
> 
> The new GIF looks good! 👍

Wow, I'm flattered. Thank You. 😎

**Pull request merged**
